---
title: "EDA2"
author: "Felipe Jorquera"
date: "13/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(Hmisc)
library(ggplot2)
library(tidyr)
library(lubridate)
setwd("C:/Users/Felipe/Documents/GitHub/2021-1/Entel---Customer-Experience")
setwd("Data plana")

f1 <- fread("7Facturacion/Fijo/Fact Fijo 2019-1.txt")
f2 <- fread("7Facturacion/Fijo/Fact Fijo 2019-2.txt")
f3 <- fread("7Facturacion/Fijo/Fact Fijo 2019-3.txt")
f4 <- fread("7Facturacion/Fijo/Fact Fijo 2020-1.txt")
f5 <- fread("7Facturacion/Fijo/Fact Fijo 2020-2.txt")
```

```{r}
churn_fijo <- fread("5Churn/Churn Fijo.txt")
facturacion_fijo <- rbind(f1, f2, f3, f4, f5)


churn_fijo <- churn_fijo %>%
  select(c(encriptado, Mes, ID_ESTADO_FACTURACION_PMF,DESC_MOVIMIENTO_ACCF,
           DESC_PRODUCTO_DEF, FACTURACION, TIPO_TRABAJO, FECHA_AR, FACT_CHURN_CODPRIN,
           SEGMENTO, SEGMENTO_
  ))

churn_fijo2 <- churn_fijo %>%
  rename(
    MES = Mes,
    PRODUCTO = DESC_PRODUCTO_DEF
  ) %>%
  group_by(encriptado, MES, PRODUCTO) %>%
  summarise(MONTO = sum(FACTURACION)) %>%
  mutate(CHURN_FIJO = 1, FECHA=(MES*100)+1)

churn_fijo$FECHA<-as.Date(as.character(churn_fijo$FECHA),format="%Y%m%d")

facturacion_fijo <- facturacion_fijo %>%
  group_by(encriptado, MES, PRODUCTO) %>%
  summarise(MONTO_F = sum(MONTO_NETO)) %>%
  mutate(FECHA=(MES*100)+1)

facturacion_fijo$FECHA<-as.Date(as.character(facturacion_fijo$FECHA),format="%Y%m%d")


cruce <- merge(x = facturacion_fijo, y = churn_fijo2,
               by = c("encriptado", "MES", 'PRODUCTO'), all.x = TRUE)
View(cruce)
cruce <- cruce %>%
  replace_na(list(CHURN_FIJO = 0))
```

## R Markdown

```{r, fig.width=10, fig.height=5, dpi=200}
xd <- churn_fijo %>%
  filter(FACTURACION < 250000)

ggplot(xd[!is.na(xd$SEGMENTO),], aes(x=FACTURACION, color=SEGMENTO))+
  geom_density(size=1)+
  labs(x='Facturación mensual', title = 'Density plot: Facturación mensual')+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r, fig.width=13, fig.height=6, dpi=300}
xd <- churn_fijo %>%
  filter(FACTURACION < 250000)

ggplot(xd[!is.na(xd$SEGMENTO),], aes(x=SEGMENTO, fill=SEGMENTO))+
  geom_bar(size=1)+
  labs(x='Clientes', title = 'Histograma: Segmentos de clientes')+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r, fig.width=13, fig.height=6, dpi=300}
xd <- facturacion_fijo %>%
  filter(MONTO_NETO < 50000, MONTO_NETO > 5000)

ggplot(xd[!is.na(xd$SUBSEGMENTO_BUN),], aes(x=MONTO_NETO, color=SUBSEGMENTO_BUN))+
  geom_density(size=1)+
  labs(x='Facturación mensual', title = 'Density plot: Segmentos de clientes')+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r, fig.width=16, fig.height=7, dpi=300}
xd <- facturacion_fijo %>%
  filter(MONTO_NETO < 100000, MONTO_NETO > 5000)

ggplot(xd[!is.na(xd$SUBSEGMENTO_BUN),], aes(y=MONTO_NETO, x=SUBSEGMENTO_BUN,
                                            fill=SUBSEGMENTO_BUN))+
  geom_boxplot(size=1)+
  labs(x='Clientes', y = 'Facturación', title = 'Boxplot: Facturación por segmentos de clientes')+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, fig.width=13, fig.height=6, dpi=300}

ggplot(xd[!is.na(xd$SUBSEGMENTO_BUN),], aes(x=SUBSEGMENTO_BUN, fill=SUBSEGMENTO_BUN))+
  geom_bar(size=1)+
  labs(x='Clientes', title = 'Histograma: Segmentos de clientes')+
  theme(plot.title = element_text(hjust = 0.5))
```