---
title: "Presentacion 3 EDA completo"
author: "Constanza Peña"
date: "11-05-2021"
output: html_document
---

```{r}
rm(list=ls())#Limpiar espacio de trabajo
graphics.off()#Borrar graficos de sesiones anteriores
library(data.table)
library(dplyr)
library(Hmisc)
library(ggplot2)
library(naniar)
library(tm)
library(tau)
library(ggpubr)
library(tidyr)

data_path="C:/Users/Asus/Documents/GitHub/Entel---Customer-Experience/Data plana/"

dir(data_path, pattern = ".txt", full.names = TRUE)
```

Subimos los datos:
```{r, warning=FALSE}
bench_resumen <- fread(paste0(data_path,"bench_resumen.txt"))
reclamos <- fread(paste0(data_path,"reclamos_str.txt"))
stock_resumen <- fread(paste0(data_path,"stock_resumen.txt"))
tracking_resumen <- fread(paste0(data_path,"tracking_resumen.txt"))
datos_bench_stock <- fread(paste0(data_path,"datos_bench_stock.txt"))

```

```{r}
colum_to_palxpal <- function (columna){
  columna <- paste(unlist(columna), collapse =" ")
  columna <- tolower(columna)
  columna <- gsub("[[:cntrl:]]", " ", columna)
  columna <- gsub('(\\s|\r|\n)+',' ',paste(unlist(columna)))
  columna <- stripWhitespace(columna)
  columna <- strsplit(columna, split =  " ") %>% unlist
  columna <- removePunctuation(columna) #se  deshace de la puntuaci?n.
  columna <- removeNumbers(columna)     #En este caso, removemos los n?meros
  columna <- removeWords(columna, words = stopwords("spanish"))
  columna <- columna[columna!=""]
  columna <- columna[columna!=" "]
  return(columna)  
}

fast.rbind <- function(...,method=c("fill","common"),value=NA){
    if("fill"==method[1]) {
        fun1 <- function(x,y,value=NA){
            x[setdiff(colnames(y),colnames(x))] <- value

            y[setdiff(colnames(x),colnames(y))] <- value

            return(rbind(x,y))
        }
    }

    if("common"==method[1]) {
        fun1 <- function(x,y,value=NULL){
          inter1 <- x %>%
            select(intersect(names(.), names(y)))
          inter2 <- y %>%
                select(intersect(names(.), names(x)))
          return(rbind(inter1,inter2))
        }
    }
    return(Reduce(function(x,y){fun1(x=x,y=y,value=value)},list(...)))
}
```

# Bench
```{r}
datos_bench_stock <- datos_bench_stock[,-c(1,2)]

names(bench_resumen)[8]<- "periodo"
names(stock_resumen)[7]<- "periodo"

datos_bench_stock <- fast.rbind(bench_resumen,stock_resumen,method="common")
datos_bench_stock[,4][datos_bench_stock[,4]=="1. Muy insatisfecho"] <- 1
datos_bench_stock[,4][datos_bench_stock[,4]=="7. Muy satisfecho"] <- 7
datos_bench_stock <-datos_bench_stock[,-c(1)]
tracking_resumen<-tracking_resumen[,-c(1)]
tracking_resumen <- subset(tracking_resumen, periodo %in% c("2020_q1","2020_q2","2019_q2","2019_q1"))

# write.table(datos_bench_stock, paste0(data_path,'datos_bench_stock.txt'), append = FALSE, sep = "\t", dec = ".",
#             row.names = TRUE, col.names = TRUE)
names(datos_bench_stock)[3] = "calificacion1"
names(tracking_resumen)[3] = "calificacion"
names(datos_bench_stock)[4] = "comentario1"
names(tracking_resumen)[4] = "comentario"
datos_bench_stock
tracking_resumen
encuestas <- merge(datos_bench_stock, tracking_resumen,
              by=c('encriptado', 'periodo'),
              all= TRUE)
```

```{r, fig.width=10, fig.height=4, dpi=1000}
seg_gol_encues <- ggplot(datos_bench_stock, aes(x=seg_gol, fill=..count..))+
  geom_bar()+
  labs(x = 'Segmento', y = 'Count', title = 'Branch: Histograma')+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5))+ theme(panel.background = element_blank())

periodo_encues <- ggplot(datos_bench_stock, aes(x=periodo, fill=..count..))+
  geom_bar()+
  labs(x = 'Periodo', y = 'Count', title = 'Branch: Histograma')+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5))+ theme(panel.background = element_blank())

figure <- ggarrange(seg_gol_encues, periodo_encues, nrow=1, ncol=2)
figure
```


```{r, fig.width=8, fig.height=3, dpi=1000}

p<-ggplot(datos_bench_stock, aes(x=`p3 pensando en su cuenta empresa, en general, con escala 1 a 7, donde 1 = muy insatisfecho y 7 = muy satisfecho, ¿cuán satisfecho está usted con entel?`, y=1, color=1)) +
  geom_boxplot()+ theme( axis.title.y = element_blank(), axis.text.y = element_blank(),axis.text.x = element_text(size=12))
p

mean(datos_bench_stock$`p3 pensando en su cuenta empresa, en general, con escala 1 a 7, donde 1 = muy insatisfecho y 7 = muy satisfecho, ¿cuán satisfecho está usted con entel?`)

g1<-qplot(y=datos_bench_stock$`p3 pensando en su cuenta empresa, en general, con escala 1 a 7, donde 1 = muy insatisfecho y 7 = muy satisfecho, ¿cuán satisfecho está usted con entel?`, x= 1, geom = "boxplot", col="blue")+ theme(panel.background = element_blank(), axis.title.y = element_blank())

ggplot(datos_bench_stock, aes(x=`p3 pensando en su cuenta empresa, en general, con escala 1 a 7, donde 1 = muy insatisfecho y 7 = muy satisfecho, ¿cuán satisfecho está usted con entel?`, y=1))+geom_boxplot()+ theme(panel.background = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank())

```

```{r}
encuestas <- datos_bench_stock[,4]
DF4 <- colum_to_palxpal(encuestas)
DF4 <-lapply(ngrams(DF4,2), paste, collapse=" ") %>% unlist
DF4 <- data.frame(table(DF4))
DF4
enc <- DF4 %>%  top_n(10, wt=Freq) %>% ungroup() 
enc <-enc[order(enc$Freq),]
enc$rownumber = 1:nrow(enc)
enc$prop <- enc$Freq/sum(enc$Freq)

head(enc)

x=15
g1<-ggplot(enc, aes(x = prop, y = reorder(DF4, prop))) + 
     geom_bar( size = 0.2,stat="identity", fill="#084cac",alpha = 1) +
  theme(axis.title.y =  element_blank(),axis.title.x =  element_blank(),axis.text.x = element_text(face="plain", color="black",size=x, angle=0, vjust = 0, hjust=0.62), axis.text.y = element_text(face="plain", color="black", 
                           size=x, angle=0, vjust = 0),plot.title = element_text(hjust = 0.5, size=15)) + ggtitle ("Encuestas") + theme(panel.background = element_blank())

g1

```


# Reclamos
```{r}
names(reclamos)
```


Veamos frecuencia de distintos tipos de reclamos
```{r}
reclamos_f <- fast.rbind(data.frame("reclamos"=reclamos$r_f_t2019),data.frame("reclamos"=reclamos$r_f_t2020)
                         ,method="common")

reclamos_f<- colum_to_palxpal(reclamos_f)
quitar <- c("na","resolutiva")
reclamos_f = reclamos_f[!(reclamos_f %in% quitar)] #un vector con cada palabra que ha aparecido en los reclamos
### Podemos ver las *palabras más comunes en los reclamos*, en particular en las columnas notas y causa

reclamos_f <- gsub("telefonico", "telefonia", reclamos_f) 
reclamos_f <- gsub("conexion", "conexión", reclamos_f)
reclamos_f <- gsub("problema", "problemas", reclamos_f)
bigramas_f <-lapply(ngrams(reclamos_f,2), paste, collapse=" ") %>% unlist
bigramas_f <- gsub("intermitencia conexion", "conexion intermitencia", bigramas_f)
bigramas_f <- gsub("intermitencia conexion", "conexion intermitencia", bigramas_f)
quitar <- c("intermitencia intermitencia","conexion conexion", "cortado cortado")
bigramas_f <- bigramas_f[!bigramas_f %in% quitar]

tabla_aux_notas <- data.frame(table(bigramas_f)) #hacemos un data frame de frecuencia de cada palabra 
reclamos_f = reclamos_f[!(reclamos_f %in% quitar)] #un vector con cada palabra que ha aparecido en los 
names(tabla_aux_notas)[2] <- "Frec"
names(tabla_aux_notas)[1] <- "palabra"

#View(tabla_aux_notas)
# Obtenemos solo las diez palabras frecuentes y ordenamos:

DF1 <- tabla_aux_notas %>%  top_n(10, wt=Frec) %>% ungroup() 
DF1 <-DF1[order(DF1$Frec),]
DF1$rownumber = 1:nrow(DF1)
DF1$prop <- prop.table(DF1$Frec)
DF1
```




```{r, fig.width=15, fig.height=4, dpi=200}
reclamos_f_com1 <-drop_na(data.frame(reclamos$r_f_com))
reclamos_f_com1 <- data.frame(table(reclamos$r_f_com))
reclamos_f_com1$prop <- round(reclamos_f_com1$Freq/sum(reclamos_f_com1$Freq),2)
reclamos_f_com1$Var1 <- tolower(reclamos_f_com1$Var1)
reclamos_f_com1


reclamos_m_teco <-drop_na(data.frame(reclamos$r_m_tecom))
reclamos_m_teco <- data.frame(table(reclamos$r_f_com))
reclamos_m_teco$prop <- round(reclamos_m_teco$Freq/sum(reclamos_m_teco$Freq),2)
reclamos_m_teco$Var1 <- tolower(reclamos_m_teco$Var1)
reclamos_m_teco
```


```{r, fig.width=10, fig.height=4, dpi=1000}
#png(paste0(data_path,"10_pal_frec_reclamos.png"), width=900,height=900)
x=12
g1<-ggplot(reclamos_f_com1, aes(x = prop, y = reorder(Var1, prop))) + 
     geom_bar( size = 0.2,stat="identity", fill="#084cac",alpha = 1) +
  theme(axis.title.y =  element_blank(),axis.title.x =  element_blank(),axis.text.x = element_text(face="plain", color="black",size=x, angle=0, vjust = 0, hjust=0.62), axis.text.y = element_text(face="plain", color="black", 
                           size=x, angle=0, vjust = 0),plot.title = element_text(hjust = 0.5, size=15)) + ggtitle ("Reclamos fijo comercial") + theme(panel.background = element_blank())

g2<-ggplot(DF1, aes(x = prop, y = reorder(palabra, prop))) + 
     geom_bar( size = 0.2,stat="identity", fill="#084cac",alpha = 1) +
  theme(axis.title.y =  element_blank(),axis.title.x =  element_blank(),axis.text.x = element_text(face="plain", color="black",size=x, angle=0, vjust = 0, hjust=0.62), axis.text.y = element_text(face="plain", color="black", 
                           size=x, angle=0, vjust = 0),plot.title = element_text(hjust = 0.5, size=15)) + ggtitle ("Reclamos fijo tecnico") + theme(panel.background = element_blank())



g3<-ggplot(reclamos_m_teco, aes(x = prop, y = reorder(Var1, prop))) + 
     geom_bar( size = 0.2,stat="identity", fill="#084cac",alpha = 1) +
  theme(axis.title.y =  element_blank(),axis.title.x =  element_blank(),axis.text.x = element_text(face="plain", color="black",size=x, angle=0, vjust = 0, hjust=0.62), axis.text.y = element_text(face="plain", color="black", 
                           size=x, angle=0, vjust = 0),plot.title = element_text(hjust = 0.5, size=15)) + ggtitle ("Reclamos movil") + theme(panel.background = element_blank())



figura <- ggarrange(g1,g2,nrow=1) 
figura
#dev.off()

```


# Tracking


```{r, fig.width=6, fig.height=4, dpi=1000}
describe(tracking_resumen$`sat entel`)
p<-ggplot(tracking_resumen, aes(x=`sat entel`, color=0)) +
  geom_histogram(fill = "#043ca4")+ theme( axis.title.x = element_blank(),
                                          axis.title.y = element_blank())+
  scale_x_continuous(limits = c(0,9),
  breaks= scales::pretty_breaks(n=10))
p

```

```{r}
tracking_resumen2 <- tracking_resumen[,5]
tracking_resumen2<- colum_to_palxpal(tracking_resumen2)

reclamos_f = reclamos_f[!(reclamos_f %in% quitar)] 

tracking_resumen2 <- gsub("s c", "sc", tracking_resumen2) 
reclamos_f <- gsub("conexion", "conexión", reclamos_f)
reclamos_f <- gsub("problema", "problemas", reclamos_f)
bigramas_f <- gsub("intermitencia conexion", "conexion intermitencia", bigramas_f)
bigramas_f <- gsub("intermitencia conexion", "conexion intermitencia", bigramas_f)

bigramas_tra <-lapply(ngrams(tracking_resumen2,2), paste, collapse=" ") %>% unlist
bigramas_tra <- bigramas_tra[!bigramas_tra %in% quitar]

bigramas_tra <- data.frame(table(bigramas_tra)) #hacemos un data frame de frecuencia de cada palabra 
quitar <- c("s c","sc sc", "sc mas","sc mejorar")
bigramas_tra = bigramas_tra[!(bigramas_tra$bigramas_tra %in% quitar)] #un vector con cada palabra que ha aparecido en los 


names(bigramas_tra)[2] <- "Frec"
names(bigramas_tra)[1] <- "palabra"

#View(tabla_aux_notas)
# Obtenemos solo las diez palabras frecuentes y ordenamos:

DF1 <- bigramas_tra %>%  top_n(10, wt=Frec) %>% ungroup() 
DF1 <-DF1[order(DF1$Frec),]
DF1$rownumber = 1:nrow(DF1)
DF1$prop <- prop.table(DF1$Frec)
DF12 <- DF1[-c(3,6,8,10),]
DF12
```

```{r, fig.width=6, fig.height=4, dpi=1000}
x=15
g1<-ggplot(DF12, aes(x = prop, y = reorder(palabra, prop))) + 
     geom_bar( size = 0.2,stat="identity", fill="#084cac",alpha = 1) +
  theme(axis.title.y =  element_blank(),axis.title.x =  element_blank(),axis.text.x = element_text(face="plain", color="black",size=x, angle=0, vjust = 0, hjust=0.62), axis.text.y = element_text(face="plain", color="black", 
                           size=x, angle=0, vjust = 0),plot.title = element_text(hjust = 0.5, size=15)) + ggtitle ("Tracking") + theme(panel.background = element_blank())
g1
```



Histograma de datos por periodo
```{r, fig.width=10, fig.height=4, dpi=1000}
r_f_t2019_hist <- ggplot(reclamos, aes(x=periodo, fill=..count..))+
  geom_bar()+
  labs( y = 'Count', title = 'Periodos en Reclamos')+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5),
        axis.text.x =   element_text(angle=45,hjust = 0.5)) + theme(panel.background = element_blank())

benchds <- ggplot(datos_bench_stock, aes(x=periodo, fill=..count..))+
  geom_bar()+
  labs( y = 'Count', title = 'Periodos en Encuestas')+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5),
        axis.text.x =   element_text(angle=45,hjust = 0.5)) + theme(panel.background = element_blank())

tradsad <- ggplot(tracking_resumen, aes(x=periodo, fill=..count..))+
  geom_bar()+
  labs( y = 'Count', title = 'Periodos en Tracking')+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5),
        axis.text.x =   element_text(angle=45,hjust = 0.5))  + theme(panel.background = element_blank())



figura <- ggarrange(benchds,r_f_t2019_hist,tradsad,nrow=1) 
figura

```

```{r}
reclamos
reclamos1 <- reclamos
reclamos1[,c("r_f_t2019","r_f_t2020","r_f_com","r_m_tecom")][!is.na(reclamos1[,c("r_f_t2019","r_f_t2020","r_f_com","r_m_tecom")])] <- 1
reclamos1[is.na(reclamos1)] <- 0
reclamos1$r_f_t2019 <- as.numeric(reclamos1$r_f_t2019)
reclamos1$r_f_t2020 <- as.numeric(reclamos1$r_f_t2020)
reclamos1$r_f_com <- as.numeric(reclamos1$r_f_com)
reclamos1$r_m_tecom <- as.numeric(reclamos1$r_m_tecom)
reclamos1$r_total<- reclamos1$r_f_t2019+reclamos1$r_f_t2020+
reclamos1$r_f_com+reclamos1$r_m_tecom


summary(tracking_resumen$`sat entel`)
```

```{r}
reclamos2 <- reclamos1[,c("encriptado","periodo","r_total")]
tracking_resumen1 <- tracking_resumen[,c("encriptado","periodo","sat entel")]
datos_bench_stock1 <- datos_bench_stock[,c("encriptado","periodo","p3 pensando en su cuenta empresa, en general, con escala 1 a 7, donde 1 = muy insatisfecho y 7 = muy satisfecho, ¿cuán satisfecho está usted con entel?")]
names(datos_bench_stock1)[3] <- "p3"



cruce1 <- merge(x = reclamos2, y = datos_bench_stock1,
               by = c("encriptado", "periodo"), all = TRUE)

cruce2 <- merge(x = cruce1, y = tracking_resumen1,
               by = c("encriptado", "periodo"), all = TRUE)
cruce2

cruce2[is.na(cruce2)] <- 0
cruce3 <- drop_na(cruce2)
cruce3 <- cruce3[,c("r_total","p3","sat entel")]
dim(cruce2)

```


```{r, fig.width=11, fig.height=4, echo= FALSE, dpi=1000}
nums <- ventas[ ,unlist(lapply(ventas, is.numeric))] #variables numéricas
ggcorr(cruce3,  label = TRUE, label_color = "white", high='blue',
       low = '#ff642c', mid = '#7F97B7',digits = 7)


```










